import random

POSITIVE = [
    "Sus Corp Reports Record-Breaking Quarterly Earnings 🚀",
    "Sus Stock Surges After CEO Announces Major Partnership 📈",
    "Sus Corp Beats Wall Street Estimates by 40% 💰",
    "Analysts Upgrade Sus Stock to 'Strong Buy' Rating ⬆️",
    "Sus Corp Lands Billion-Dollar Government Contract 🏛️",
    "Sus Industries Announces Revolutionary New Product Line 🔬",
    "Sus Corp Share Buyback Program Sends Stock Soaring 📈",
    "Institutional Investors Pour Billions Into Sus Stock 💸",
    "Sus Corp CEO Receives 'Innovator of the Year' Award 🏆",
    "Sus Corp Expands Into 15 New International Markets 🌍",
    "Sus Stock Hits All-Time High Amid Bull Market Rally 🐂",
    "Sus Corp Announces 50% Dividend Increase for Shareholders 💵",
    "Sus Corp Partners With Tech Giants in Historic Deal 🤝",
    "Legendary Investor Warren Buffet Buys Sus Corp Stake 🧓",
    "Sus Corp Revenue Up 200% Year-Over-Year 📊",
    "Sus Corp Awarded Major Defense Contract Worth $2 Billion 🛡️",
    "Market Analysts: Sus Stock Could Double by Year End 📈",
    "Sus Corp Beats Earnings for 12th Consecutive Quarter 🏅",
    "Sus Corp Acquires Rival Firm in Landmark Deal 🤝",
    "Sus Corp Announces Plans for Stock Split Amid Surge 📈",
    "Hedge Funds Increase Sus Stock Holdings by 300% 💰",
    "Sus Corp's New AI Technology Gets Global Praise 🤖",
    "Sus Corp Secures Exclusive Patent Worth Billions 📜",
    "Analysts Say Sus Corp Is 'Most Undervalued Stock of the Decade' 💎",
    "Sus Corp Announces Record Dividend Payout 🎉",
    "Retail Investors Rally Behind Sus Stock in Short Squeeze 🚀",
    "Sus Corp Launches IPO of Subsidiary at 10x Valuation 💵",
    "Sus Corp Signs $500M Deal With Global Retailer 🏪",
    "Sus Corp's New CEO Sends Stock Up 30% on First Day 📈",
    "Sus Corp Wins Historic Antitrust Ruling in Its Favor ⚖️",
    "Sus Industries Posts Strongest Quarterly Growth in History 🔝",
    "Major Pension Fund Adds Sus Stock as Core Holding 🏦",
    "Sus Corp Announces Plans to Triple Workforce 👷",
    "Sus Corp Unveils Groundbreaking Green Energy Initiative 🌱",
    "Sus Corp Crushes Earnings: EPS Up 150% 💥",
    "Moody's Upgrades Sus Corp Credit Rating to AAA 🌟",
    "Sus Corp's New Product Goes Viral Overnight 🦠",
    "Activist Investors Push Sus Corp to Unlock Hidden Value 💎",
    "Sus Corp Revenues Hit $10 Billion Milestone 🎯",
    "Big Banks Initiate Coverage of Sus Stock With 'Buy' Rating 🏦",
    "Sus Corp Announces Special $5 Dividend Per Share 💵",
    "Sus Corp Wins National Innovation Award 🏆",
    "Sus Stock Added to S&P 500 Index 📊",
    "Sus Corp Announces Share Repurchase of $1 Billion 💰",
    "Sus Corp CEO Buys Massive Stake, Signals Confidence 📈",
    "Sus Corp Expands Revenue Stream With New Subscription Model 💡",
    "Sus Corp's Breakthrough Patent Reshapes the Industry 🔬",
    "Sus Corp Signs Record-Breaking Export Deal 🌐",
    "Sus Corp Announces Joint Venture With Tech Giant 💻",
    "Short Sellers Squeezed as Sus Stock Rockets Higher 🚀",
    "Sus Corp's Market Cap Doubles in One Quarter 💰",
    "Sus Corp Beats Revenue Expectations by $500M 📈",
    "Sus Corp Named Most Trusted Brand of the Year 🏅",
    "Billionaire Investor Says Sus Stock Is 'Once in a Generation' Buy 💎",
    "Sus Corp Files 47 New Patents This Quarter 📜",
    "Sus Corp Announces Merger That Creates Industry Giant 🤝",
    "Federal Reserve Cuts Rates, Sus Stock Benefits Immediately 📈",
    "Sus Corp Achieves Carbon Neutral Status, ESG Funds Buy In 🌿",
    "Sus Corp's Streaming Service Hits 100M Subscribers 🎬",
    "Retail Traders Flood Into Sus Stock After Viral Moment 🔥",
    "Sus Corp's Chief Scientist Wins Nobel Prize 🏅",
    "Sus Corp Secures $2B in Venture Capital Funding 💰",
    "Sus Corp's Robotics Division Posts 500% Revenue Growth 🤖",
    "Wall Street Raises Sus Corp Price Target to $500 🎯",
    "Sus Corp Announces Surprise Earnings Beat 💥",
    "Sus Corp Board Approves Massive Buyback Program 📈",
    "Sus Corp Teams Up With Space Agency on New Project 🚀",
    "Sus Corp Posts Biggest Sales Day in Company History 🛍️",
    "Sus Corp's Drone Division Gets FAA Clearance 🚁",
    "Sus Corp Announces 3-for-1 Stock Split 📊",
    "Sus Corp Named to Fortune 500 for First Time 🏆",
    "Sovereign Wealth Fund Invests $5B Into Sus Corp 🌍",
    "Sus Corp Lands Exclusive Deal With Major Sports League ⚽",
    "Sus Corp's Supply Chain Improvements Cut Costs by 40% 📉",
    "Sus Corp Acquires AI Startup in All-Stock Deal 💡",
    "Sus Corp Reports Zero Debt for First Time in Decade 💳",
    "Sus Corp Wins $3B Government Infrastructure Contract 🏗️",
    "Major Retailer Signs 10-Year Exclusive Deal With Sus Corp 🏪",
    "Sus Corp's Cloud Division Revenue Triples 📊",
    "Sus Corp Announces Partnership With Elon Musk Venture 🚀",
    "Sus Corp Shares Jump 20% After Surprise Announcement 📈",
    "Sus Corp Successfully Launches New Product in Record Time ⚡",
    "Sus Corp's Annual Revenue Grows 80% Year-Over-Year 📊",
    "Sus Corp Opens Mega Factory Creating 50,000 Jobs 🏭",
    "Sus Corp Completes $4B Acquisition Ahead of Schedule 🎯",
    "Inflation Data Boosts Sus Corp Outlook Significantly 📈",
    "Sus Corp's Healthcare Division Gets FDA Approval 💊",
    "Sus Corp Lands Partnership With World's Largest Bank 🏦",
    "Sus Corp's EV Division Ships First 100,000 Units 🚗",
    "Sus Corp Returns $10B to Shareholders This Quarter 💵",
    "Consumer Confidence Surge Boosts Sus Corp Sales 🛒",
    "Sus Corp Announces $1B Investment in R&D 🔬",
    "Sus Corp's New App Downloads Surpass 50 Million 📱",
    "Sus Corp Voted Most Innovative Company of the Year 🏅",
    "Sus Corp Profit Margins Expand to Record 45% 📈",
    "Bulls Pile Into Sus Stock on Positive Economic Data 🐂",
    "Sus Corp Beats Analyst Estimates Across All Divisions 💥",
    "Sus Corp's Founder Returns to Lead Company Into New Era 👑",
    "Sus Corp Announces Plans to Double Revenue by Next Year 📊",
    "Sus Corp's Self-Driving Technology Gets Green Light 🚘",
    "Record Options Activity Signals Major Sus Stock Rally Ahead 🎯",
]

NEGATIVE = [
    "Sus Corp CEO Caught Being Extremely Sus 📉",
    "Sus Corp Misses Earnings by Massive Margin 💸",
    "Whistleblower Exposes Sus Corp's Accounting Fraud ⚠️",
    "Sus Corp Faces $5 Billion Lawsuit from Regulators ⚖️",
    "Short Sellers Target Sus Corp in Brutal Report 🐻",
    "Sus Corp CFO Resigns Amid Financial Scandal 🚨",
    "Sus Corp Data Breach Exposes 50 Million Users 🔓",
    "Analysts Downgrade Sus Stock to 'Strong Sell' ⬇️",
    "Sus Corp Revenue Collapses in Worst Quarter Ever 📉",
    "Sus Corp Announces Mass Layoffs of 30% of Workforce 😢",
    "Sus Corp Supply Chain Completely Falls Apart 🏭",
    "SEC Launches Investigation Into Sus Corp Practices 🔍",
    "Sus Corp's Top Product Recalled Nationwide 🛑",
    "Sus Corp Loses Billion-Dollar Contract to Rival 💔",
    "Sus Corp Board of Directors in Open Revolt 🔥",
    "Sus Corp's CEO Arrested for Insider Trading 🚔",
    "Sus Corp Misses Revenue Estimates for 5th Quarter in a Row 📉",
    "Sus Corp's Factory Catches Fire, Production Halted 🔥",
    "Sus Corp Facing Class Action Lawsuit from Investors ⚖️",
    "Sus Corp's Market Share Drops 30% to Competitor 📊",
    "Sus Corp's Flagship Product Gets Catastrophic Reviews 1⭐",
    "Sus Corp Announces Dividend Cut Amid Cash Crisis 💔",
    "Sus Corp's New CEO Dumps All Shares Within Days 🚩",
    "Inflation Crushes Sus Corp's Already Thin Margins 📉",
    "Sus Corp Files for Chapter 11 Bankruptcy Protection 💀",
    "Federal Regulators Fine Sus Corp $2 Billion 🏛️",
    "Sus Corp's Supply Chain Partner Goes Bankrupt 💸",
    "Hedge Fund Publishes Damning Short Report on Sus Corp 🐻",
    "Sus Corp's Flagship Store Closes Permanently 🏪",
    "Recession Fears Tank Sus Corp Stock 10% 😱",
    "Sus Corp's AI Product Turns Out to Be Complete Fraud 🤖",
    "Sus Corp Slashes Revenue Guidance by 50% 📉",
    "Sus Corp Loses Major Government Contract 🏛️",
    "Sus Corp's Cybersecurity Breach Costs $1 Billion 🔓",
    "Analyst: Sus Corp Has 'Zero Path to Profitability' 😬",
    "Sus Corp Cancels Annual Dividend, Stock Tanks 📉",
    "Sus Corp's New Product Launch Ends in Disaster 💥",
    "Sus Corp Board Rejects Merger, Investors Furious 😡",
    "Sus Corp's CEO Takes $50M Bonus While Cutting Jobs 🤑",
    "Trade War Sanctions Cripple Sus Corp Supply Chain 🌍",
    "Sus Corp Caught Lying About Environmental Compliance 🌿",
    "Sus Corp's Key Patent Invalidated by Federal Court ⚖️",
    "Sus Corp Posts Biggest Loss in Company History 📉",
    "Major Hedge Fund Bets $2B Against Sus Corp 🐻",
    "Sus Corp's Streaming Service Loses 10M Subscribers 📺",
    "Sus Corp Reports Zero Revenue Growth for Entire Year 😐",
    "Sus Corp's Drug Trial Fails in Phase 3 💊",
    "Sus Corp Accused of Price Gouging by Senator 🏛️",
    "Sus Corp's Robotics Division Completely Shuts Down 🤖",
    "Activist Investor Calls Sus Corp 'Uninvestable' 🚩",
    "Sus Corp's Credit Rating Cut to Junk Status 💀",
    "Sus Corp Withdraws IPO of Subsidiary at Last Minute 📉",
    "Sus Corp's App Suffers 3-Day Outage 📱",
    "Consumer Group Boycotts Sus Corp Products 🛒",
    "Sus Corp Forced to Settle $3B Antitrust Case ⚖️",
    "Sus Corp's Self-Driving Car Involved in 50 Accidents 🚗",
    "Sus Corp's Global Operations Investigated for Fraud 🔍",
    "Sus Corp's Factory Workers Go on Nationwide Strike 👷",
    "Sus Corp's Largest Customer Switches to Competitor 💔",
    "Sus Corp Delays Product Launch by 18 Months ⏰",
    "Sus Corp's Board Rejects Shareholder Proposals for 3rd Year 😤",
    "Sus Corp Loses $500M in Trading Scandal 💸",
    "Extreme Weather Destroys Sus Corp's Main Facility 🌪️",
    "Sus Corp Faces Massive Cybersecurity Class Action 🔓",
    "Sus Corp's Growth Flatlines Completely 📊",
    "Sus Corp's Chief Scientist Indicted for Fraud 🔬",
    "Sus Corp Loses Flagship Customer Worth $1B Annually 💔",
    "Rising Rates Crush Sus Corp's Debt-Laden Balance Sheet 💸",
    "Sus Corp Recalls Products in 40 Countries Simultaneously 🌍",
    "Sus Corp's Healthcare Division Fails FDA Approval 💊",
    "Federal Probe Into Sus Corp Expands to 5 Countries 🌐",
    "Sus Corp's Revenue Forecast Downgraded 3 Times in One Day 📉",
    "Sus Corp's Founder Sells Entire Stake in Company 🚩",
    "Sus Corp Misses Debt Payment, Stocks Tank 15% 💸",
    "Sus Corp Faces Backlash Over Misleading Advertising 📢",
    "Sus Corp's Cloud Service Suffers Catastrophic Breach 🔓",
    "Sus Corp's Annual Report Reveals Hidden Losses 📋",
    "Sus Corp's Merger Collapses at Last Minute 💔",
    "Dow Jones Removes Sus Corp From Major Index 📉",
    "Sus Corp's New CEO Announces Massive Restructuring 🔄",
    "Sus Corp's Production Line Contaminated, Operations Halted 🏭",
    "Unemployment Spike Hammers Sus Corp's Consumer Division 📉",
    "Sus Corp Faces Congressional Hearing on Data Practices 🏛️",
    "Sus Corp Loses $750M Arbitration Case 💸",
    "Sus Corp's Drone Program Grounded by Regulators 🚁",
    "Sus Corp Announces Emergency Asset Sale to Raise Cash 💰",
    "Sus Corp's Stock Removed from Retirement Fund Portfolios 📉",
    "Major Analyst Firm Cuts Sus Corp Price Target to $5 📉",
    "Sus Corp's New Payment System Hacked on Day One 🔓",
    "Sus Corp Slashes R&D Budget Amid Financial Woes 🔬",
    "Sus Corp's EV Division Burns Through Cash Reserves ⚡",
    "Economic Slowdown Hits Sus Corp's Sales Hard 😰",
    "Sus Corp Quietly Sells Headquarters Building 🏢",
    "Sus Corp's Flagship Store Robbed in Embarrassing Heist 🎭",
    "SEC Freezes Sus Corp's Assets Pending Investigation 🔍",
    "Sus Corp's Supply Shortage Triggers Profit Warning 📉",
    "Sus Corp Forced to Restate 5 Years of Financial Data 📋",
    "Investors File Emergency Motion Against Sus Corp Board ⚖️",
    "Sus Corp's Biggest Bull Turns Bearish, Dumps All Shares 🐻",
]


def get_headline(positive: bool) -> str:
    pool = POSITIVE if positive else NEGATIVE
    return random.choice(pool)
